<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>nodejs</AssemblyName>
    <RootNamespace>nodejs</RootNamespace>
    <Version>1.0.3</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- Package settings -->
    <IsPackable>true</IsPackable>
    <PackageId>Tsonic.Nodejs</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../js-runtime/src/Tsonic.JSRuntime/Tsonic.JSRuntime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
